package project;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class BeerPage extends javax.swing.JFrame {
    public BeerPage() {
        initComponents();
    }
    
    public String user;
    public BeerPage(String user){
        initComponents();
        this.user=user;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel19 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Heineken_button = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cart_label = new javax.swing.JLabel();
        back_button = new javax.swing.JButton();
        corona_button = new javax.swing.JButton();
        item7 = new javax.swing.JButton();
        budweiser_button = new javax.swing.JButton();
        Hoegaarden_button = new javax.swing.JButton();
        item6 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        quan4 = new javax.swing.JComboBox<>();
        quan2 = new javax.swing.JComboBox<>();
        quan3 = new javax.swing.JComboBox<>();
        quan1 = new javax.swing.JComboBox<>();
        quan5 = new javax.swing.JComboBox<>();
        quan6 = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        quan7 = new javax.swing.JComboBox<>();
        quan8 = new javax.swing.JComboBox<>();
        quan9 = new javax.swing.JComboBox<>();
        item8 = new javax.swing.JButton();
        item9 = new javax.swing.JButton();
        item4 = new javax.swing.JButton();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();

        jLabel19.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel19.setText("Price : $");

        jLabel23.setText("jLabel22");

        jLabel25.setText("jLabel22");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(103, 0, 0));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/SideLogo.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/Mainlogo.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel5.setText("One stop for all your alcohol related needs.......");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel3)
                        .addContainerGap(127, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Sitka Text", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(103, 0, 0));
        jLabel6.setText("BEER");

        jPanel6.setBackground(new java.awt.Color(102, 0, 0));
        jPanel6.setForeground(new java.awt.Color(103, 0, 0));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1024, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/beer_corona.jpg"))); // NOI18N
        jLabel7.setText("jLabel6");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/beer_king.jpg"))); // NOI18N

        Heineken_button.setBackground(new java.awt.Color(248, 148, 6));
        Heineken_button.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Heineken_button.setForeground(new java.awt.Color(255, 255, 255));
        Heineken_button.setText("Add to Cart");
        Heineken_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Heineken_buttonActionPerformed(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/beer_hein.png"))); // NOI18N

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/beer_bud.jpg"))); // NOI18N

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/beer_asahi.jpg"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/beer_hoe.jpg"))); // NOI18N

        cart_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/cart.png"))); // NOI18N
        cart_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cart_labelMouseClicked(evt);
            }
        });

        back_button.setBackground(new java.awt.Color(103, 0, 0));
        back_button.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        back_button.setForeground(new java.awt.Color(255, 255, 255));
        back_button.setText("BACK");
        back_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_buttonActionPerformed(evt);
            }
        });

        corona_button.setBackground(new java.awt.Color(248, 148, 6));
        corona_button.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        corona_button.setForeground(new java.awt.Color(255, 255, 255));
        corona_button.setText("Add to Cart");
        corona_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                corona_buttonActionPerformed(evt);
            }
        });

        item7.setBackground(new java.awt.Color(248, 148, 6));
        item7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        item7.setForeground(new java.awt.Color(255, 255, 255));
        item7.setText("Add to Cart");
        item7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item7ActionPerformed(evt);
            }
        });

        budweiser_button.setBackground(new java.awt.Color(248, 148, 6));
        budweiser_button.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        budweiser_button.setForeground(new java.awt.Color(255, 255, 255));
        budweiser_button.setText("Add to Cart");
        budweiser_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                budweiser_buttonActionPerformed(evt);
            }
        });

        Hoegaarden_button.setBackground(new java.awt.Color(248, 148, 6));
        Hoegaarden_button.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Hoegaarden_button.setForeground(new java.awt.Color(255, 255, 255));
        Hoegaarden_button.setText("Add to Cart");
        Hoegaarden_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Hoegaarden_buttonActionPerformed(evt);
            }
        });

        item6.setBackground(new java.awt.Color(248, 148, 6));
        item6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        item6.setForeground(new java.awt.Color(255, 255, 255));
        item6.setText("Add to Cart");
        item6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item6ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setText("Price : $ 3");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel4.setText("Price : $ 5");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel10.setText("Price : $ 3");

        jLabel15.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel15.setText("    Hoegaarden");

        jLabel16.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel16.setText("      Kingfisher");

        jLabel21.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel21.setText("     Corona Extra");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel22.setText("Quantity:");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel24.setText("Quantity:");

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel26.setText("Quantity:");

        jLabel27.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel27.setText("       Heineken");

        jLabel28.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel28.setText("          Asahi");

        jLabel29.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel29.setText("        Budweiser");

        jLabel30.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel30.setText("Price : $ 1");

        jLabel31.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel31.setText("Price : $ 1");

        jLabel32.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel32.setText("Price : $ 5");

        jLabel33.setText("Quantity :");

        jLabel34.setText("Quantity:");

        jLabel35.setText("Quantity :");

        quan4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6" }));

        quan2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6" }));

        quan3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6" }));

        quan1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6" }));

        quan5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6" }));

        quan6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6" }));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/beer_carlsberg.JPG"))); // NOI18N

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/beer_foster.png"))); // NOI18N

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/beer_guiness.jpg"))); // NOI18N

        jLabel20.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel20.setText("Price : $ 2");

        jLabel36.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel36.setText("Price : $ 2");

        jLabel37.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel37.setText("Price : $ 2");

        jLabel38.setText("Quantity :");

        jLabel39.setText("Quantity :");

        jLabel40.setText("Quantity :");

        quan7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6" }));

        quan8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6" }));

        quan9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6" }));

        item8.setBackground(new java.awt.Color(248, 148, 6));
        item8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        item8.setForeground(new java.awt.Color(255, 255, 255));
        item8.setText("Add to Cart");
        item8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item8ActionPerformed(evt);
            }
        });

        item9.setBackground(new java.awt.Color(248, 148, 6));
        item9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        item9.setForeground(new java.awt.Color(255, 255, 255));
        item9.setText("Add to Cart");
        item9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item9ActionPerformed(evt);
            }
        });

        item4.setBackground(new java.awt.Color(248, 148, 6));
        item4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        item4.setForeground(new java.awt.Color(255, 255, 255));
        item4.setText("Add to Cart");
        item4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item4ActionPerformed(evt);
            }
        });

        jLabel41.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel41.setText("      Fosters");

        jLabel42.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel42.setText("   Guinness");

        jLabel43.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel43.setText("     Carlberg");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(back_button, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cart_label)
                .addGap(20, 20, 20))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(item4)
                .addGap(240, 240, 240)
                .addComponent(budweiser_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(item6)
                .addGap(121, 121, 121))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(Heineken_button)
                        .addGap(248, 248, 248)
                        .addComponent(Hoegaarden_button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(corona_button)
                        .addGap(128, 128, 128))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(quan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel33)
                                .addGap(18, 18, 18)
                                .addComponent(quan4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(142, 142, 142)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel29, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(jLabel24)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(quan2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(jLabel34)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(quan5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel39)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(quan8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addComponent(jLabel35)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(quan6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(80, 80, 80))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(quan3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(204, 204, 204))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel40)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(quan9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(205, 205, 205))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(item7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(item8)
                .addGap(207, 207, 207)
                .addComponent(item9)
                .addGap(140, 140, 140))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel38)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(quan7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(121, 121, 121)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(768, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(back_button)
                    .addComponent(cart_label, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel26)
                                    .addComponent(quan2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(quan3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Hoegaarden_button)
                                    .addComponent(corona_button)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel22)
                                    .addComponent(quan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Heineken_button)))
                        .addGap(60, 60, 60)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel33)
                                                    .addComponent(quan4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel34)
                                                    .addComponent(quan5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(budweiser_button)
                                                .addComponent(item6))
                                            .addComponent(item4)))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel35)
                                            .addComponent(quan6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel36)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(quan7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel38)
                                    .addComponent(jLabel39)
                                    .addComponent(quan8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(item9))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(item8)
                                            .addComponent(item7)))))
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(quan9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel40))
                        .addGap(71, 71, 71))))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(509, 509, 509)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1186, Short.MAX_VALUE)))
        );

        jScrollPane2.setViewportView(jPanel5);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1200, 1100);

        setSize(new java.awt.Dimension(1201, 1101));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void item6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item6ActionPerformed
        // TODO add your handling code here:
        int quan =Integer.parseInt(quan6.getSelectedItem().toString());       
        
        String p_name= "Asahi";
        String p_price = "5";
        String p_type = "Beer";
        try {            
                Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95");               
                String query="select stock from product_list where product_name='"+p_name+"'";
                PreparedStatement pre=con.prepareStatement(query);
                ResultSet re=pre.executeQuery();
                if(re.next()){
                    int stockx =Integer.parseInt(re.getString("stock"));
                    
                    if(stockx == 0 || stockx < quan)
                        JOptionPane.showMessageDialog(null,"Item is out of stock");
                    else{
                        try {
                            Class.forName("oracle.jdbc.OracleDriver");
                            Connection con2=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95");               
                            String query2="update cart_table set quantity = quantity + '"+quan+"' where product_name='"+p_name+"'and  exists (select product_name from cart_table where username ='"+user+"' and product_name='"+p_name+"') ";
                            PreparedStatement pre2=con2.prepareStatement(query2);
                            ResultSet rs=pre2.executeQuery();
                            if(rs.next()){
                                Connection con3=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95"); 
                                Statement stat=con3.createStatement();
                                stat.executeUpdate("update product_list set stock = stock - '"+quan+"' where product_name ='"+p_name+"' and exists (select product_name from cart_table  where username ='"+user+"' and product_name='"+p_name+"')");
                                stat.executeUpdate("update cart_table set price = price + '"+p_price+"' * '"+quan+"' where product_name = '"+p_name+"' ");
                                JOptionPane.showMessageDialog(null,"Item added to cart");
                                con3.close();
                            }
                            con2.close();
                        }catch (ClassNotFoundException | SQLException ex) {                           
                                Connection con4=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95");
                                Statement stat2=con4.createStatement();
                                stat2.executeUpdate("insert into cart_table(username,product_name,quantity,price,pro_type) values ('"+user+"','"+p_name+"','"+quan+"','"+p_price+"','"+p_type+"')");
                                stat2.executeUpdate("update product_list set stock = stock - '"+quan+"' where product_name ='"+p_name+"' ");
                                stat2.executeUpdate("update cart_table set price =  '"+p_price+"' * '"+quan+"' where product_name = '"+p_name+"' ");
                                JOptionPane.showMessageDialog(null,"Item added to cart");
                                con4.close();
                            Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
                        } 
                        
                    }
                    con.close();    
                }                
        }
        catch (SQLException ex) {
                Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
        }         
    }//GEN-LAST:event_item6ActionPerformed

    private void Hoegaarden_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Hoegaarden_buttonActionPerformed
        // TODO add your handling code here:
        int quan =Integer.parseInt(quan2.getSelectedItem().toString());       
        
        String p_name= "Hoegaarden";
        int p_price = 3;
        String p_type = "Beer";
        try {            
                Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95");               
                String query="select stock from product_list where product_name='"+p_name+"'";
                PreparedStatement pre=con.prepareStatement(query);
                ResultSet re=pre.executeQuery();
                if(re.next()){
                    int stockx =Integer.parseInt(re.getString("stock"));
                    
                    if(stockx == 0 || stockx < quan)
                        JOptionPane.showMessageDialog(null,"Item is out of stock");
                    else{
                        try {
                            Class.forName("oracle.jdbc.OracleDriver");
                            Connection con2=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95");               
                            String query2="update cart_table set quantity = quantity + '"+quan+"' where product_name='"+p_name+"' and exists (select product_name from cart_table where username ='"+user+"' and product_name='"+p_name+"') ";
                            PreparedStatement pre2=con2.prepareStatement(query2);
                            ResultSet rs=pre2.executeQuery();
                            if(rs.next()){
                                Connection con3=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95"); 
                                Statement stat=con3.createStatement();
                                stat.executeUpdate("update product_list set stock = stock - '"+quan+"' where product_name ='"+p_name+"' and exists (select product_name from cart_table  where username ='"+user+"' and product_name='"+p_name+"')");
                                stat.executeUpdate("update cart_table set price = price + '"+p_price+"' * '"+quan+"' where product_name = '"+p_name+"' ");
                                JOptionPane.showMessageDialog(null,"Item added to cart");
                                
                                con3.close();
                            }
                            con2.close();
                        }catch (ClassNotFoundException | SQLException ex) {                           
                                Connection con4=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95");
                                Statement stat2=con4.createStatement();
                                stat2.executeUpdate("insert into cart_table(username,product_name,quantity,price,pro_type) values ('"+user+"','"+p_name+"','"+quan+"','"+p_price+"','"+p_type+"')");
                                stat2.executeUpdate("update product_list set stock = stock - '"+quan+"' where product_name ='"+p_name+"' ");
                                stat2.executeUpdate("update cart_table set price =  '"+p_price+"' * '"+quan+"' where product_name = '"+p_name+"' ");
                                JOptionPane.showMessageDialog(null,"Item added to cart");
                                con4.close();
                            Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
                        } 
                        
                    }
                    con.close();    
                }                
        }
        catch (SQLException ex) {
                Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Hoegaarden_buttonActionPerformed

    private void budweiser_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_budweiser_buttonActionPerformed
        // TODO add your handling code here:
        int quan =Integer.parseInt(quan5.getSelectedItem().toString());       
        
        String p_name= "Budweiser";
        String p_price = "1";
        String p_type = "Beer";
        try {            
                Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95");               
                String query="select stock from product_list where product_name='"+p_name+"'";
                PreparedStatement pre=con.prepareStatement(query);
                ResultSet re=pre.executeQuery();
                if(re.next()){
                    int stockx =Integer.parseInt(re.getString("stock"));
                    
                    if(stockx == 0 || stockx < quan)
                        JOptionPane.showMessageDialog(null,"Item is out of stock");
                    else{
                        try {
                            Class.forName("oracle.jdbc.OracleDriver");
                            Connection con2=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95");               
                            String query2="update cart_table set quantity = quantity + '"+quan+"' where product_name='"+p_name+"'and  exists (select product_name from cart_table where username ='"+user+"' and product_name='"+p_name+"') ";
                            PreparedStatement pre2=con2.prepareStatement(query2);
                            ResultSet rs=pre2.executeQuery();
                            if(rs.next()){
                                Connection con3=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95"); 
                                Statement stat=con3.createStatement();
                                stat.executeUpdate("update product_list set stock = stock - '"+quan+"' where product_name ='"+p_name+"' and exists (select product_name from cart_table  where username ='"+user+"' and product_name='"+p_name+"')");
                                stat.executeUpdate("update cart_table set price = price + '"+p_price+"' * '"+quan+"' where product_name = '"+p_name+"' ");
                                JOptionPane.showMessageDialog(null,"Item added to cart");
                                con3.close();
                            }
                            con2.close();
                        }catch (ClassNotFoundException | SQLException ex) {                           
                                Connection con4=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95");
                                Statement stat2=con4.createStatement();
                                stat2.executeUpdate("insert into cart_table(username,product_name,quantity,price,pro_type) values ('"+user+"','"+p_name+"','"+quan+"','"+p_price+"','"+p_type+"')");
                                stat2.executeUpdate("update product_list set stock = stock - '"+quan+"' where product_name ='"+p_name+"' ");
                                stat2.executeUpdate("update cart_table set price =  '"+p_price+"' * '"+quan+"' where product_name = '"+p_name+"' ");
                                JOptionPane.showMessageDialog(null,"Item added to cart");
                                con4.close();
                            Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
                        } 
                        
                    }
                    con.close();    
                }                
        }
        catch (SQLException ex) {
                Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_budweiser_buttonActionPerformed

    private void item7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item7ActionPerformed
        // TODO add your handling code here:
        int quan =Integer.parseInt(quan7.getSelectedItem().toString());       
        
        String p_name= "Carlsberg";
        String p_price = "2";
        String p_type = "Beer";
        try {            
                Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95");               
                String query="select stock from product_list where product_name='"+p_name+"'";
                PreparedStatement pre=con.prepareStatement(query);
                ResultSet re=pre.executeQuery();
                if(re.next()){
                    int stockx =Integer.parseInt(re.getString("stock"));
                    
                    if(stockx == 0 || stockx < quan)
                        JOptionPane.showMessageDialog(null,"Item is out of stock");
                    else{
                        try {
                            Class.forName("oracle.jdbc.OracleDriver");
                            Connection con2=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95");               
                            String query2="update cart_table set quantity = quantity + '"+quan+"' where product_name='"+p_name+"'and  exists (select product_name from cart_table where username ='"+user+"' and product_name='"+p_name+"') ";
                            PreparedStatement pre2=con2.prepareStatement(query2);
                            ResultSet rs=pre2.executeQuery();
                            if(rs.next()){
                                Connection con3=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95"); 
                                Statement stat=con3.createStatement();
                                stat.executeUpdate("update product_list set stock = stock - '"+quan+"' where product_name ='"+p_name+"' and exists (select product_name from cart_table  where username ='"+user+"' and product_name='"+p_name+"')");
                                stat.executeUpdate("update cart_table set price = price + '"+p_price+"' * '"+quan+"' where product_name = '"+p_name+"' ");
                                JOptionPane.showMessageDialog(null,"Item added to cart");
                                con3.close();
                            }
                            con2.close();
                        }catch (ClassNotFoundException | SQLException ex) {                           
                                Connection con4=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95");
                                Statement stat2=con4.createStatement();
                                stat2.executeUpdate("insert into cart_table(username,product_name,quantity,price,pro_type) values ('"+user+"','"+p_name+"','"+quan+"','"+p_price+"','"+p_type+"')");
                                stat2.executeUpdate("update product_list set stock = stock - '"+quan+"' where product_name ='"+p_name+"' ");
                                stat2.executeUpdate("update cart_table set price =  '"+p_price+"' * '"+quan+"' where product_name = '"+p_name+"' ");
                                JOptionPane.showMessageDialog(null,"Item added to cart");
                                con4.close();
                            Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
                        } 
                        
                    }
                    con.close();    
                }                
        }
        catch (SQLException ex) {
                Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_item7ActionPerformed

    private void corona_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_corona_buttonActionPerformed
        // TODO add your handling code here:
        int quan =Integer.parseInt(quan3.getSelectedItem().toString());       
        
        String p_name= "Corona Extra";
        String p_price = "5";
        String p_type = "Beer";

        try {            
                Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95");               
                String query="select stock from product_list where product_name='"+p_name+"'";
                PreparedStatement pre=con.prepareStatement(query);
                ResultSet re=pre.executeQuery();
                if(re.next()){
                    int stockx =Integer.parseInt(re.getString("stock"));
                    
                    if(stockx == 0 || stockx < quan)
                        JOptionPane.showMessageDialog(null,"Item is out of stock");
                    else{
                        try {
                            Class.forName("oracle.jdbc.OracleDriver");
                            Connection con2=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95");               
                            String query2="update cart_table set quantity = quantity + '"+quan+"' where product_name='"+p_name+"'and  exists (select product_name from cart_table where username ='"+user+"' and product_name='"+p_name+"') ";
                            PreparedStatement pre2=con2.prepareStatement(query2);
                            ResultSet rs=pre2.executeQuery();
                            if(rs.next()){
                                Connection con3=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95"); 
                                Statement stat=con3.createStatement();
                                stat.executeUpdate("update product_list set stock = stock - '"+quan+"' where product_name ='"+p_name+"' and exists (select product_name from cart_table  where username ='"+user+"' and product_name='"+p_name+"')");
                                stat.executeUpdate("update cart_table set price = price+ '"+p_price+"' * '"+quan+"' where product_name = '"+p_name+"' ");
                                JOptionPane.showMessageDialog(null,"Item added to cart");
                                con3.close();
                            }
                            con2.close();
                        }catch (ClassNotFoundException | SQLException ex) {                           
                                Connection con4=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95");
                                Statement stat2=con4.createStatement();
                                stat2.executeUpdate("insert into cart_table(username,product_name,quantity,price,pro_type) values ('"+user+"','"+p_name+"','"+quan+"','"+p_price+"','"+p_type+"')");
                                stat2.executeUpdate("update product_list set stock = stock - '"+quan+"' where product_name ='"+p_name+"' ");
                                stat2.executeUpdate("update cart_table set price =  '"+p_price+"' * '"+quan+"' where product_name = '"+p_name+"' ");
                                JOptionPane.showMessageDialog(null,"Item added to cart");
                                con4.close();
                            Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
                        } 
                        
                    }
                    con.close();    
                }                
        }
        catch (SQLException ex) {
                Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
        }       
    }//GEN-LAST:event_corona_buttonActionPerformed

    private void cart_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cart_labelMouseClicked

        Cart r =new Cart(user);
        r.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cart_labelMouseClicked

    private void Heineken_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Heineken_buttonActionPerformed
        int quan =Integer.parseInt(quan1.getSelectedItem().toString());       
        
        String p_name= "Heineken";
        String p_price = "3";
        String p_type = "Beer";
        try {            
                Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95");               
                String query="select stock from product_list where product_name='"+p_name+"'";
                PreparedStatement pre=con.prepareStatement(query);
                ResultSet re=pre.executeQuery();
                if(re.next()){
                    int stockx =Integer.parseInt(re.getString("stock"));
                    
                    if(stockx == 0 || stockx < quan)
                        JOptionPane.showMessageDialog(null,"Item is out of stock");
                    else{
                        try {
                            Class.forName("oracle.jdbc.OracleDriver");
                            Connection con2=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95");               
                            String query2="update cart_table set quantity = quantity + '"+quan+"' where product_name='"+p_name+"'and  exists (select product_name from cart_table where username ='"+user+"' and product_name='"+p_name+"') ";
                            PreparedStatement pre2=con2.prepareStatement(query2);
                            ResultSet rs=pre2.executeQuery();
                            if(rs.next()){
                                Connection con3=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95"); 
                                Statement stat=con3.createStatement();
                                stat.executeUpdate("update product_list set stock = stock - '"+quan+"' where product_name ='"+p_name+"' and exists (select product_name from cart_table  where username ='"+user+"' and product_name='"+p_name+"')");
                                stat.executeUpdate("update cart_table set price = price + '"+p_price+"' * '"+quan+"' where product_name = '"+p_name+"' ");
                                JOptionPane.showMessageDialog(null,"Item added to cart");
                                con3.close();
                            }
                            con2.close();
                        }catch (ClassNotFoundException | SQLException ex) {                           
                                Connection con4=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95");
                                Statement stat2=con4.createStatement();
                                stat2.executeUpdate("insert into cart_table(username,product_name,quantity,price,pro_type) values ('"+user+"','"+p_name+"','"+quan+"','"+p_price+"','"+p_type+"')");
                                stat2.executeUpdate("update product_list set stock = stock - '"+quan+"' where product_name ='"+p_name+"' ");
                                stat2.executeUpdate("update cart_table set price = '"+p_price+"' * '"+quan+"' where product_name = '"+p_name+"' ");
                                JOptionPane.showMessageDialog(null,"Item added to cart");
                                con4.close();
                            Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
                        } 
                        
                    }
                    con.close();    
                }                
        }
        catch (SQLException ex) {
                Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
        }      
    }//GEN-LAST:event_Heineken_buttonActionPerformed

    private void back_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_buttonActionPerformed
        MainPage r =new MainPage(user);
        r.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_back_buttonActionPerformed

    private void item8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item8ActionPerformed
        // TODO add your handling code here:
        int quan =Integer.parseInt(quan8.getSelectedItem().toString());       
        
        String p_name= "Fosters";
        String p_price = "2";
        String p_type = "Beer";
        try {            
                Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95");               
                String query="select stock from product_list where product_name='"+p_name+"'";
                PreparedStatement pre=con.prepareStatement(query);
                ResultSet re=pre.executeQuery();
                if(re.next()){
                    int stockx =Integer.parseInt(re.getString("stock"));
                    
                    if(stockx == 0 || stockx < quan)
                        JOptionPane.showMessageDialog(null,"Item is out of stock");
                    else{
                        try {
                            Class.forName("oracle.jdbc.OracleDriver");
                            Connection con2=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95");               
                            String query2="update cart_table set quantity = quantity + '"+quan+"' where product_name='"+p_name+"'and  exists (select product_name from cart_table where username ='"+user+"' and product_name='"+p_name+"') ";
                            PreparedStatement pre2=con2.prepareStatement(query2);
                            ResultSet rs=pre2.executeQuery();
                            if(rs.next()){
                                Connection con3=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95"); 
                                Statement stat=con3.createStatement();
                                stat.executeUpdate("update product_list set stock = stock - '"+quan+"' where product_name ='"+p_name+"' and exists (select product_name from cart_table  where username ='"+user+"' and product_name='"+p_name+"')");
                                stat.executeUpdate("update cart_table set price = price + '"+p_price+"' * '"+quan+"' where product_name = '"+p_name+"' ");
                                JOptionPane.showMessageDialog(null,"Item added to cart");
                                con3.close();
                            }
                            con2.close();
                        }catch (ClassNotFoundException | SQLException ex) {                           
                                Connection con4=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95");
                                Statement stat2=con4.createStatement();
                                stat2.executeUpdate("insert into cart_table(username,product_name,quantity,price,pro_type) values ('"+user+"','"+p_name+"','"+quan+"','"+p_price+"','"+p_type+"')");
                                stat2.executeUpdate("update product_list set stock = stock - '"+quan+"' where product_name ='"+p_name+"' ");
                                stat2.executeUpdate("update cart_table set price =  '"+p_price+"' * '"+quan+"' where product_name = '"+p_name+"' ");
                                JOptionPane.showMessageDialog(null,"Item added to cart");
                                con4.close();
                            Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
                        } 
                        
                    }
                    con.close();    
                }                
        }
        catch (SQLException ex) {
                Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_item8ActionPerformed

    private void item9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item9ActionPerformed
        // TODO add your handling code here:
        int quan =Integer.parseInt(quan9.getSelectedItem().toString());       
        
        String p_name= "Guinness";
        String p_price = "2";
        String p_type = "Beer";
        try {            
                Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95");               
                String query="select stock from product_list where product_name='"+p_name+"'";
                PreparedStatement pre=con.prepareStatement(query);
                ResultSet re=pre.executeQuery();
                if(re.next()){
                    int stockx =Integer.parseInt(re.getString("stock"));
                    
                    if(stockx == 0 || stockx < quan)
                        JOptionPane.showMessageDialog(null,"Item is out of stock");
                    else{
                        try {
                            Class.forName("oracle.jdbc.OracleDriver");
                            Connection con2=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95");               
                            String query2="update cart_table set quantity = quantity + '"+quan+"' where product_name='"+p_name+"'and  exists (select product_name from cart_table where username ='"+user+"' and product_name='"+p_name+"') ";
                            PreparedStatement pre2=con2.prepareStatement(query2);
                            ResultSet rs=pre2.executeQuery();
                            if(rs.next()){
                                Connection con3=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95"); 
                                Statement stat=con3.createStatement();
                                stat.executeUpdate("update product_list set stock = stock - '"+quan+"' where product_name ='"+p_name+"' and exists (select product_name from cart_table  where username ='"+user+"' and product_name='"+p_name+"')");
                                stat.executeUpdate("update cart_table set price = price + '"+p_price+"' * '"+quan+"' where product_name = '"+p_name+"' ");
                                JOptionPane.showMessageDialog(null,"Item added to cart");
                                con3.close();
                            }
                            con2.close();
                        }catch (ClassNotFoundException | SQLException ex) {                           
                                Connection con4=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95");
                                Statement stat2=con4.createStatement();
                                stat2.executeUpdate("insert into cart_table(username,product_name,quantity,price,pro_type) values ('"+user+"','"+p_name+"','"+quan+"','"+p_price+"','"+p_type+"')");
                                stat2.executeUpdate("update product_list set stock = stock - '"+quan+"' where product_name ='"+p_name+"' ");
                                stat2.executeUpdate("update cart_table set price =  '"+p_price+"' * '"+quan+"' where product_name = '"+p_name+"' ");
                                JOptionPane.showMessageDialog(null,"Item added to cart");
                                con4.close();
                            Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
                        } 
                        
                    }
                    con.close();    
                }                
        }
        catch (SQLException ex) {
                Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_item9ActionPerformed

    private void item4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item4ActionPerformed
        // TODO add your handling code here:
        int quan =Integer.parseInt(quan4.getSelectedItem().toString());       
        
        String p_name= "Kingfisher";
        String p_price = "1";
        String p_type = "Beer";
        try {            
                Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95");               
                String query="select stock from product_list where product_name='"+p_name+"'";
                PreparedStatement pre=con.prepareStatement(query);
                ResultSet re=pre.executeQuery();
                if(re.next()){
                    int stockx =Integer.parseInt(re.getString("stock"));
                    
                    if(stockx == 0 || stockx < quan)
                        JOptionPane.showMessageDialog(null,"Item is out of stock");
                    else{
                        try {
                            Class.forName("oracle.jdbc.OracleDriver");
                            Connection con2=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95");               
                            String query2="update cart_table set quantity = quantity + '"+quan+"' where product_name='"+p_name+"'and  exists (select product_name from cart_table where username ='"+user+"' and product_name='"+p_name+"') ";
                            PreparedStatement pre2=con2.prepareStatement(query2);
                            ResultSet rs=pre2.executeQuery();
                            if(rs.next()){
                                Connection con3=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95"); 
                                Statement stat=con3.createStatement();
                                stat.executeUpdate("update product_list set stock = stock - '"+quan+"' where product_name ='"+p_name+"' and exists (select product_name from cart_table  where username ='"+user+"' and product_name='"+p_name+"')");
                                stat.executeUpdate("update cart_table set price = price + '"+p_price+"' * '"+quan+"' where product_name = '"+p_name+"' ");
                                JOptionPane.showMessageDialog(null,"Item added to cart");
                                con3.close();
                            }
                            con2.close();
                        }catch (ClassNotFoundException | SQLException ex) {                           
                                Connection con4=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95");
                                Statement stat2=con4.createStatement();
                                stat2.executeUpdate("insert into cart_table(username,product_name,quantity,price,pro_type) values ('"+user+"','"+p_name+"','"+quan+"','"+p_price+"','"+p_type+"')");
                                stat2.executeUpdate("update product_list set stock = stock - '"+quan+"' where product_name ='"+p_name+"' ");
                                stat2.executeUpdate("update cart_table set price =  ('"+p_price+"' * '"+quan+"') where product_name = '"+p_name+"' ");
                                JOptionPane.showMessageDialog(null,"Item added to cart");
                                con4.close();
                            Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
                        } 
                        
                    }
                    con.close();    
                }                
        }
        catch (SQLException ex) {
                Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_item4ActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BeerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BeerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BeerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BeerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BeerPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Heineken_button;
    private javax.swing.JButton Hoegaarden_button;
    private javax.swing.JButton back_button;
    private javax.swing.JButton budweiser_button;
    private javax.swing.JLabel cart_label;
    private javax.swing.JButton corona_button;
    private javax.swing.JButton item4;
    private javax.swing.JButton item6;
    private javax.swing.JButton item7;
    private javax.swing.JButton item8;
    private javax.swing.JButton item9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> quan1;
    private javax.swing.JComboBox<String> quan2;
    private javax.swing.JComboBox<String> quan3;
    private javax.swing.JComboBox<String> quan4;
    private javax.swing.JComboBox<String> quan5;
    private javax.swing.JComboBox<String> quan6;
    private javax.swing.JComboBox<String> quan7;
    private javax.swing.JComboBox<String> quan8;
    private javax.swing.JComboBox<String> quan9;
    // End of variables declaration//GEN-END:variables
}
