package project;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class LiquorPage extends javax.swing.JFrame {
    public LiquorPage() {
        initComponents();
    }
    String user;
    public LiquorPage(String user){
        initComponents();
        this.user=user;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        item1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cart_label = new javax.swing.JLabel();
        back_button = new javax.swing.JButton();
        item3 = new javax.swing.JButton();
        item5 = new javax.swing.JButton();
        item2 = new javax.swing.JButton();
        item6 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        item4 = new javax.swing.JButton();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(103, 0, 0));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/SideLogo.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/Mainlogo.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel5.setText("One stop for all your alcohol related needs.......");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Sitka Text", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(103, 0, 0));
        jLabel6.setText("LIQUOR");

        jPanel6.setBackground(new java.awt.Color(102, 0, 0));
        jPanel6.setForeground(new java.awt.Color(103, 0, 0));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1024, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/PIERRE FERRAND 1ER CRU DE COGNAC 1840 liquer.jpg"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/baileys-original-irish-cream-liqueur.jpg"))); // NOI18N

        item1.setBackground(new java.awt.Color(248, 148, 6));
        item1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        item1.setForeground(new java.awt.Color(255, 255, 255));
        item1.setText("Add to Cart");
        item1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item1ActionPerformed(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/Moët & Chandon champagne.jpg"))); // NOI18N

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/Cointreau__.jpg"))); // NOI18N

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/patron_tequila_silver.jpg"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/hibiki.jpg"))); // NOI18N

        cart_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/cart.png"))); // NOI18N
        cart_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cart_labelMouseClicked(evt);
            }
        });

        back_button.setBackground(new java.awt.Color(103, 0, 0));
        back_button.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        back_button.setForeground(new java.awt.Color(255, 255, 255));
        back_button.setText("BACK");
        back_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_buttonActionPerformed(evt);
            }
        });

        item3.setBackground(new java.awt.Color(248, 148, 6));
        item3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        item3.setForeground(new java.awt.Color(255, 255, 255));
        item3.setText("Add to Cart");
        item3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item3ActionPerformed(evt);
            }
        });

        item5.setBackground(new java.awt.Color(248, 148, 6));
        item5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        item5.setForeground(new java.awt.Color(255, 255, 255));
        item5.setText("Add to Cart");
        item5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item5ActionPerformed(evt);
            }
        });

        item2.setBackground(new java.awt.Color(248, 148, 6));
        item2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        item2.setForeground(new java.awt.Color(255, 255, 255));
        item2.setText("Add to Cart");
        item2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item2ActionPerformed(evt);
            }
        });

        item6.setBackground(new java.awt.Color(248, 148, 6));
        item6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        item6.setForeground(new java.awt.Color(255, 255, 255));
        item6.setText("Add to Cart");
        item6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item6ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setText("Price : $ 30");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel4.setText("Price : $ 30");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel10.setText("Price : $ 50");

        jLabel15.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel15.setText("           Hibiki");

        jLabel16.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel16.setText("Bailey's Irish Cream");

        jLabel21.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel21.setText("    Piere Ferrand");

        jLabel27.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel27.setText("   Moët & Chandon ");

        jLabel28.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel28.setText("           Patron");

        jLabel29.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel29.setText("      Contreau");

        jLabel30.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel30.setText("Price : $ 30");

        jLabel31.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel31.setText("Price : $ 30");

        jLabel32.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel32.setText("Price : $ 30");

        item4.setBackground(new java.awt.Color(248, 148, 6));
        item4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        item4.setForeground(new java.awt.Color(255, 255, 255));
        item4.setText("Add to Cart");
        item4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(back_button, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cart_label)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 53, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(37, 37, 37))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(133, 133, 133)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(445, 445, 445))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(104, 104, 104))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(111, 111, 111)))
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                            .addGap(13, 13, 13)
                                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel16)
                                                .addGroup(jPanel5Layout.createSequentialGroup()
                                                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel5Layout.createSequentialGroup()
                                                    .addGap(38, 38, 38)
                                                    .addComponent(item1))
                                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel5Layout.createSequentialGroup()
                                                    .addGap(158, 158, 158)
                                                    .addComponent(item2))
                                                .addGroup(jPanel5Layout.createSequentialGroup()
                                                    .addGap(150, 150, 150)
                                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel5Layout.createSequentialGroup()
                                                    .addGap(150, 150, 150)
                                                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                .addGap(100, 100, 100)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(12, 12, 12)))
                                        .addGap(80, 80, 80))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                        .addComponent(item3)
                                        .addGap(148, 148, 148))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(91, 91, 91))))))))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(item4)
                .addGap(216, 216, 216)
                .addComponent(item5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(item6)
                .addGap(117, 117, 117))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(back_button)
                    .addComponent(cart_label, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)))
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(jLabel15)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(item1)
                    .addComponent(item2)
                    .addComponent(item3))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel12)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(item4)
                    .addComponent(item5)
                    .addComponent(item6))
                .addGap(91, 91, 91))
        );

        jScrollPane2.setViewportView(jPanel5);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1139, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 798, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(1200, 1708));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void item1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item1ActionPerformed
        int quan =1;       
        
        String p_name="Moet & Chandon";
        String p_price = "50";
        String p_type = "Liquor";
        try {            
                Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95");               
                String query="select stock from product_list where product_name='"+p_name+"'";
                PreparedStatement pre=con.prepareStatement(query);
                ResultSet re=pre.executeQuery();
                if(re.next()){
                    int stockx =Integer.parseInt(re.getString("stock"));
                    
                    if(stockx == 0 || stockx < quan)
                        JOptionPane.showMessageDialog(null,"Item is out of stock");
                    else{
                        try {
                            Class.forName("oracle.jdbc.OracleDriver");
                            Connection con2=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95");               
                            String query2="update cart_table set quantity = quantity + '"+quan+"' where product_name='"+p_name+"'and  exists (select product_name from cart_table where username ='"+user+"' and product_name='"+p_name+"') ";
                            PreparedStatement pre2=con2.prepareStatement(query2);
                            ResultSet rs=pre2.executeQuery();
                            if(rs.next()){
                                Connection con3=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95"); 
                                Statement stat=con3.createStatement();
                                stat.executeUpdate("update product_list set stock = stock - '"+quan+"' where product_name ='"+p_name+"' and exists (select product_name from cart_table  where username ='"+user+"' and product_name='"+p_name+"')");
                                stat.executeUpdate("update cart_table set price = price + '"+p_price+"' * '"+quan+"' where product_name = '"+p_name+"' ");
                                JOptionPane.showMessageDialog(null,"Item added to cart");
                                con3.close();
                            }
                            con2.close();
                        }catch (ClassNotFoundException | SQLException ex) {                           
                                Connection con4=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95");
                                Statement stat2=con4.createStatement();
                                stat2.executeUpdate("insert into cart_table(username,product_name,quantity,price,pro_type) values ('"+user+"','"+p_name+"','"+quan+"','"+p_price+"','"+p_type+"')");
                                stat2.executeUpdate("update product_list set stock = stock - '"+quan+"' where product_name ='"+p_name+"' ");
                                stat2.executeUpdate("update cart_table set price =  ('"+p_price+"' * '"+quan+"') where product_name = '"+p_name+"' ");
                                JOptionPane.showMessageDialog(null,"Item added to cart");
                                con4.close();
                            Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
                        } 
                        
                    }
                    con.close();    
                }                
        }
        catch (SQLException ex) {
                Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_item1ActionPerformed

    private void cart_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cart_labelMouseClicked

        Cart r =new Cart(user);
        r.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cart_labelMouseClicked

    private void back_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_buttonActionPerformed
        MainPage r =new MainPage(user);
        r.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_back_buttonActionPerformed

    private void item3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item3ActionPerformed
        // TODO add your handling code here:
        int quan =1;       
        
        String p_name= "Cointreau";
        String p_price = "30";
        String p_type = "Liquor";
        try {            
                Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95");               
                String query="select stock from product_list where product_name='"+p_name+"'";
                PreparedStatement pre=con.prepareStatement(query);
                ResultSet re=pre.executeQuery();
                if(re.next()){
                    int stockx =Integer.parseInt(re.getString("stock"));
                    
                    if(stockx == 0 || stockx < quan)
                        JOptionPane.showMessageDialog(null,"Item is out of stock");
                    else{
                        try {
                            Class.forName("oracle.jdbc.OracleDriver");
                            Connection con2=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95");               
                            String query2="update cart_table set quantity = quantity + '"+quan+"' where product_name='"+p_name+"'and  exists (select product_name from cart_table where username ='"+user+"' and product_name='"+p_name+"') ";
                            PreparedStatement pre2=con2.prepareStatement(query2);
                            ResultSet rs=pre2.executeQuery();
                            if(rs.next()){
                                Connection con3=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95"); 
                                Statement stat=con3.createStatement();
                                stat.executeUpdate("update product_list set stock = stock - '"+quan+"' where product_name ='"+p_name+"' and exists (select product_name from cart_table  where username ='"+user+"' and product_name='"+p_name+"')");
                                stat.executeUpdate("update cart_table set price = price + '"+p_price+"' * '"+quan+"' where product_name = '"+p_name+"' ");
                                JOptionPane.showMessageDialog(null,"Item added to cart");
                                con3.close();
                            }
                            con2.close();
                        }catch (ClassNotFoundException | SQLException ex) {                           
                                Connection con4=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95");
                                Statement stat2=con4.createStatement();
                                stat2.executeUpdate("insert into cart_table(username,product_name,quantity,price,pro_type) values ('"+user+"','"+p_name+"','"+quan+"','"+p_price+"','"+p_type+"')");
                                stat2.executeUpdate("update product_list set stock = stock - '"+quan+"' where product_name ='"+p_name+"' ");
                                stat2.executeUpdate("update cart_table set price =  ('"+p_price+"' * '"+quan+"') where product_name = '"+p_name+"' ");
                                JOptionPane.showMessageDialog(null,"Item added to cart");
                                con4.close();
                            Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
                        } 
                        
                    }
                    con.close();    
                }                
        }
        catch (SQLException ex) {
                Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_item3ActionPerformed

    private void item5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item5ActionPerformed
        // TODO add your handling code here:
        int quan =1;       
        
        String p_name= "Pierra Ferrand";
        String p_price = "30";
        String p_type = "Liquor";
        try {            
                Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95");               
                String query="select stock from product_list where product_name='"+p_name+"'";
                PreparedStatement pre=con.prepareStatement(query);
                ResultSet re=pre.executeQuery();
                if(re.next()){
                    int stockx =Integer.parseInt(re.getString("stock"));
                    
                    if(stockx == 0 || stockx < quan)
                        JOptionPane.showMessageDialog(null,"Item is out of stock");
                    else{
                        try {
                            Class.forName("oracle.jdbc.OracleDriver");
                            Connection con2=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95");               
                            String query2="update cart_table set quantity = quantity + '"+quan+"' where product_name='"+p_name+"'and  exists (select product_name from cart_table where username ='"+user+"' and product_name='"+p_name+"') ";
                            PreparedStatement pre2=con2.prepareStatement(query2);
                            ResultSet rs=pre2.executeQuery();
                            if(rs.next()){
                                Connection con3=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95"); 
                                Statement stat=con3.createStatement();
                                stat.executeUpdate("update product_list set stock = stock - '"+quan+"' where product_name ='"+p_name+"' and exists (select product_name from cart_table  where username ='"+user+"' and product_name='"+p_name+"')");
                                stat.executeUpdate("update cart_table set price = price + '"+p_price+"' * '"+quan+"' where product_name = '"+p_name+"' ");
                                JOptionPane.showMessageDialog(null,"Item added to cart");
                                con3.close();
                            }
                            con2.close();
                        }catch (ClassNotFoundException | SQLException ex) {                           
                                Connection con4=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95");
                                Statement stat2=con4.createStatement();
                                stat2.executeUpdate("insert into cart_table(username,product_name,quantity,price,pro_type) values ('"+user+"','"+p_name+"','"+quan+"','"+p_price+"','"+p_type+"')");
                                stat2.executeUpdate("update product_list set stock = stock - '"+quan+"' where product_name ='"+p_name+"' ");
                                stat2.executeUpdate("update cart_table set price =  ('"+p_price+"' * '"+quan+"') where product_name = '"+p_name+"' ");
                                JOptionPane.showMessageDialog(null,"Item added to cart");
                                con4.close();
                            Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
                        } 
                        
                    }
                    con.close();    
                }                
        }
        catch (SQLException ex) {
                Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_item5ActionPerformed

    private void item2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item2ActionPerformed
        // TODO add your handling code here:
        int quan =1;       
        
        String p_name= "Hibiki Whiskey";
        String p_price = "30";
        String p_type = "Liquor";
        try {            
                Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95");               
                String query="select stock from product_list where product_name='"+p_name+"'";
                PreparedStatement pre=con.prepareStatement(query);
                ResultSet re=pre.executeQuery();
                if(re.next()){
                    int stockx =Integer.parseInt(re.getString("stock"));
                    
                    if(stockx == 0 || stockx < quan)
                        JOptionPane.showMessageDialog(null,"Item is out of stock");
                    else{
                        try {
                            Class.forName("oracle.jdbc.OracleDriver");
                            Connection con2=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95");               
                            String query2="update cart_table set quantity = quantity + '"+quan+"' where product_name='"+p_name+"'and  exists (select product_name from cart_table where username ='"+user+"' and product_name='"+p_name+"') ";
                            PreparedStatement pre2=con2.prepareStatement(query2);
                            ResultSet rs=pre2.executeQuery();
                            if(rs.next()){
                                Connection con3=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95"); 
                                Statement stat=con3.createStatement();
                                stat.executeUpdate("update product_list set stock = stock - '"+quan+"' where product_name ='"+p_name+"' and exists (select product_name from cart_table  where username ='"+user+"' and product_name='"+p_name+"')");
                                stat.executeUpdate("update cart_table set price = price + '"+p_price+"' * '"+quan+"' where product_name = '"+p_name+"' ");
                                JOptionPane.showMessageDialog(null,"Item added to cart");
                                con3.close();
                            }
                            con2.close();
                        }catch (ClassNotFoundException | SQLException ex) {                           
                                Connection con4=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95");
                                Statement stat2=con4.createStatement();
                                stat2.executeUpdate("insert into cart_table(username,product_name,quantity,price,pro_type) values ('"+user+"','"+p_name+"','"+quan+"','"+p_price+"','"+p_type+"')");
                                stat2.executeUpdate("update product_list set stock = stock - '"+quan+"' where product_name ='"+p_name+"' ");
                                stat2.executeUpdate("update cart_table set price =  ('"+p_price+"' * '"+quan+"') where product_name = '"+p_name+"' ");
                                JOptionPane.showMessageDialog(null,"Item added to cart");
                                con4.close();
                            Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
                        } 
                        
                    }
                    con.close();    
                }                
        }
        catch (SQLException ex) {
                Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_item2ActionPerformed

    private void item6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item6ActionPerformed
        // TODO add your handling code here:
        int quan =1;       
        
        String p_name= "Patron Tequila";
        String p_price = "30";
        String p_type = "Liquor";
        try {            
                Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95");               
                String query="select stock from product_list where product_name='"+p_name+"'";
                PreparedStatement pre=con.prepareStatement(query);
                ResultSet re=pre.executeQuery();
                if(re.next()){
                    int stockx =Integer.parseInt(re.getString("stock"));
                    
                    if(stockx == 0 || stockx < quan)
                        JOptionPane.showMessageDialog(null,"Item is out of stock");
                    else{
                        try {
                            Class.forName("oracle.jdbc.OracleDriver");
                            Connection con2=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95");               
                            String query2="update cart_table set quantity = quantity + '"+quan+"' where product_name='"+p_name+"'and  exists (select product_name from cart_table where username ='"+user+"' and product_name='"+p_name+"') ";
                            PreparedStatement pre2=con2.prepareStatement(query2);
                            ResultSet rs=pre2.executeQuery();
                            if(rs.next()){
                                Connection con3=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95"); 
                                Statement stat=con3.createStatement();
                                stat.executeUpdate("update product_list set stock = stock - '"+quan+"' where product_name ='"+p_name+"' and exists (select product_name from cart_table  where username ='"+user+"' and product_name='"+p_name+"')");
                                stat.executeUpdate("update cart_table set price = price + '"+p_price+"' * '"+quan+"' where product_name = '"+p_name+"' ");
                                JOptionPane.showMessageDialog(null,"Item added to cart");
                                con3.close();
                            }
                            con2.close();
                        }catch (ClassNotFoundException | SQLException ex) {                           
                                Connection con4=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95");
                                Statement stat2=con4.createStatement();
                                stat2.executeUpdate("insert into cart_table(username,product_name,quantity,price,pro_type) values ('"+user+"','"+p_name+"','"+quan+"','"+p_price+"','"+p_type+"')");
                                stat2.executeUpdate("update product_list set stock = stock - '"+quan+"' where product_name ='"+p_name+"' ");
                                stat2.executeUpdate("update cart_table set price =  ('"+p_price+"' * '"+quan+"') where product_name = '"+p_name+"' ");
                                JOptionPane.showMessageDialog(null,"Item added to cart");
                                con4.close();
                            Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
                        } 
                        
                    }
                    con.close();    
                }                
        }
        catch (SQLException ex) {
                Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_item6ActionPerformed

    private void item4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item4ActionPerformed
        // TODO add your handling code here:
        int quan =1;       
        
        String p_name= "Baileys Original";
        String p_price = "30";
        String p_type = "Liquor";
        try {            
                Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95");               
                String query="select stock from product_list where product_name='"+p_name+"'";
                PreparedStatement pre=con.prepareStatement(query);
                ResultSet re=pre.executeQuery();
                if(re.next()){
                    int stockx =Integer.parseInt(re.getString("stock"));
                    
                    if(stockx == 0 || stockx < quan)
                        JOptionPane.showMessageDialog(null,"Item is out of stock");
                    else{
                        try {
                            Class.forName("oracle.jdbc.OracleDriver");
                            Connection con2=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95");               
                            String query2="update cart_table set quantity = quantity + '"+quan+"' where product_name='"+p_name+"'and  exists (select product_name from cart_table where username ='"+user+"' and product_name='"+p_name+"') ";
                            PreparedStatement pre2=con2.prepareStatement(query2);
                            ResultSet rs=pre2.executeQuery();
                            if(rs.next()){
                                Connection con3=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95"); 
                                Statement stat=con3.createStatement();
                                stat.executeUpdate("update product_list set stock = stock - '"+quan+"' where product_name ='"+p_name+"' and exists (select product_name from cart_table  where username ='"+user+"' and product_name='"+p_name+"')");
                                stat.executeUpdate("update cart_table set price = price + '"+p_price+"' * '"+quan+"' where product_name = '"+p_name+"' ");
                                JOptionPane.showMessageDialog(null,"Item added to cart");
                                con3.close();
                            }
                            con2.close();
                        }catch (ClassNotFoundException | SQLException ex) {                           
                                Connection con4=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95");
                                Statement stat2=con4.createStatement();
                                stat2.executeUpdate("insert into cart_table(username,product_name,quantity,price,pro_type) values ('"+user+"','"+p_name+"','"+quan+"','"+p_price+"','"+p_type+"')");
                                stat2.executeUpdate("update product_list set stock = stock - '"+quan+"' where product_name ='"+p_name+"' ");
                                stat2.executeUpdate("update cart_table set price =  ('"+p_price+"' * '"+quan+"') where product_name = '"+p_name+"' ");
                                JOptionPane.showMessageDialog(null,"Item added to cart");
                                con4.close();
                            Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
                        } 
                        
                    }
                    con.close();    
                }                
        }
        catch (SQLException ex) {
                Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_item4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LiquorPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LiquorPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LiquorPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LiquorPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LiquorPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_button;
    private javax.swing.JLabel cart_label;
    private javax.swing.JButton item1;
    private javax.swing.JButton item2;
    private javax.swing.JButton item3;
    private javax.swing.JButton item4;
    private javax.swing.JButton item5;
    private javax.swing.JButton item6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
