package project;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class RumPage extends javax.swing.JFrame {
    public RumPage() {
        initComponents();
    }
    String user;
    public RumPage(String user) {
        initComponents();
        this.user=user;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        item1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cart_label = new javax.swing.JLabel();
        back_button = new javax.swing.JButton();
        item3 = new javax.swing.JButton();
        item7 = new javax.swing.JButton();
        item5 = new javax.swing.JButton();
        item2 = new javax.swing.JButton();
        item6 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        item8 = new javax.swing.JButton();
        item9 = new javax.swing.JButton();
        item4 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(103, 0, 0));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/SideLogo.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/Mainlogo.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel5.setText("One stop for all your alcohol related needs.......");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Sitka Text", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(103, 0, 0));
        jLabel6.setText("RUM");

        jPanel6.setBackground(new java.awt.Color(102, 0, 0));
        jPanel6.setForeground(new java.awt.Color(103, 0, 0));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1024, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/plantationpineapplerum.jpg"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/mountgayrum.jpg"))); // NOI18N

        item1.setBackground(new java.awt.Color(248, 148, 6));
        item1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        item1.setForeground(new java.awt.Color(255, 255, 255));
        item1.setText("Add to Cart");
        item1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item1ActionPerformed(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/sailorjerryspicedrum.jpg"))); // NOI18N

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/goslings_rum.png"))); // NOI18N

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/old_monk_rum.jpg"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/el dorado rum.jpg"))); // NOI18N

        cart_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/cart.png"))); // NOI18N
        cart_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cart_labelMouseClicked(evt);
            }
        });

        back_button.setBackground(new java.awt.Color(103, 0, 0));
        back_button.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        back_button.setForeground(new java.awt.Color(255, 255, 255));
        back_button.setText("BACK");
        back_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_buttonActionPerformed(evt);
            }
        });

        item3.setBackground(new java.awt.Color(248, 148, 6));
        item3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        item3.setForeground(new java.awt.Color(255, 255, 255));
        item3.setText("Add to Cart");
        item3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item3ActionPerformed(evt);
            }
        });

        item7.setBackground(new java.awt.Color(248, 148, 6));
        item7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        item7.setForeground(new java.awt.Color(255, 255, 255));
        item7.setText("Add to Cart");
        item7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item7ActionPerformed(evt);
            }
        });

        item5.setBackground(new java.awt.Color(248, 148, 6));
        item5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        item5.setForeground(new java.awt.Color(255, 255, 255));
        item5.setText("Add to Cart");
        item5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item5ActionPerformed(evt);
            }
        });

        item2.setBackground(new java.awt.Color(248, 148, 6));
        item2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        item2.setForeground(new java.awt.Color(255, 255, 255));
        item2.setText("Add to Cart");
        item2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item2ActionPerformed(evt);
            }
        });

        item6.setBackground(new java.awt.Color(248, 148, 6));
        item6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        item6.setForeground(new java.awt.Color(255, 255, 255));
        item6.setText("Add to Cart");
        item6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item6ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setText("Price : $ 30");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel4.setText("Price : $ 40");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel10.setText("Price : $ 50");

        jLabel15.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel15.setText("     El. Dorado");

        jLabel16.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel16.setText("  Mount Gay");

        jLabel21.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel21.setText(" Plantation Pineapple");

        jLabel27.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel27.setText("    Sailor Jerry");

        jLabel28.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel28.setText("    Old Monk");

        jLabel29.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel29.setText("     Goslings");

        jLabel30.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel30.setText("Price : $ 50");

        jLabel31.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel31.setText("Price : $ 30");

        jLabel32.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel32.setText("Price : $ 15");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/captainmorganrum.jpg"))); // NOI18N

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/bacardirum.png"))); // NOI18N

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/malibucoconutrum.jpg"))); // NOI18N

        jLabel20.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel20.setText("Price : $ 25");

        jLabel36.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel36.setText("Price : $ 20");

        jLabel37.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel37.setText("Price : $20");

        item8.setBackground(new java.awt.Color(248, 148, 6));
        item8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        item8.setForeground(new java.awt.Color(255, 255, 255));
        item8.setText("Add to Cart");
        item8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item8ActionPerformed(evt);
            }
        });

        item9.setBackground(new java.awt.Color(248, 148, 6));
        item9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        item9.setForeground(new java.awt.Color(255, 255, 255));
        item9.setText("Add to Cart");
        item9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item9ActionPerformed(evt);
            }
        });

        item4.setBackground(new java.awt.Color(248, 148, 6));
        item4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        item4.setForeground(new java.awt.Color(255, 255, 255));
        item4.setText("Add to Cart");
        item4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item4ActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel19.setText("Captain Morgan");

        jLabel23.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel23.setText("Bacardi Rum");

        jLabel25.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel25.setText("Mailbu Rum");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(item7)
                .addGap(225, 225, 225)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(item8)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel19)
                                .addComponent(item1)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(item4))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(198, 198, 198)
                                .addComponent(item5)
                                .addGap(234, 234, 234)
                                .addComponent(item6))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(item9)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel37)
                                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(26, 26, 26))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(161, 161, 161)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(back_button, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(870, 870, 870)
                                .addComponent(cart_label))
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(145, 145, 145)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(149, 149, 149)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(item2)
                                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                                        .addGap(177, 177, 177)
                                                        .addComponent(item3))
                                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                                        .addGap(142, 142, 142)
                                                        .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                                        .addGap(124, 124, 124)
                                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                                        .addGap(122, 122, 122)
                                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel21)
                                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))))))))))
                .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(121, 121, 121)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(758, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(back_button)
                    .addComponent(cart_label, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(33, 33, 33)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(item2)
                    .addComponent(item3)
                    .addComponent(item1))
                .addGap(75, 75, 75)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(item4)
                            .addComponent(item5)
                            .addComponent(item6)))
                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36)
                    .addComponent(jLabel37))
                .addGap(45, 45, 45)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(item8)
                    .addComponent(item7)
                    .addComponent(item9))
                .addContainerGap(131, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(509, 509, 509)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1292, Short.MAX_VALUE)))
        );

        jScrollPane2.setViewportView(jPanel5);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 774, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1200, 1070);

        setSize(new java.awt.Dimension(1200, 1072));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void item1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item1ActionPerformed
        int quan =1;       
        
        String p_name= "Sailor Jerry";
        String p_price = "30";
        String p_type = "Rum";
        try {            
                Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95");               
                String query="select stock from product_list where product_name='"+p_name+"'";
                PreparedStatement pre=con.prepareStatement(query);
                ResultSet re=pre.executeQuery();
                if(re.next()){
                    int stockx =Integer.parseInt(re.getString("stock"));
                    
                    if(stockx == 0 || stockx < quan)
                        JOptionPane.showMessageDialog(null,"Item is out of stock");
                    else{
                        try {
                            Class.forName("oracle.jdbc.OracleDriver");
                            Connection con2=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95");               
                            String query2="update cart_table set quantity = quantity + '"+quan+"' where product_name='"+p_name+"'and  exists (select product_name from cart_table where username ='"+user+"' and product_name='"+p_name+"') ";
                            PreparedStatement pre2=con2.prepareStatement(query2);
                            ResultSet rs=pre2.executeQuery();
                            if(rs.next()){
                                Connection con3=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95"); 
                                Statement stat=con3.createStatement();
                                stat.executeUpdate("update product_list set stock = stock - '"+quan+"' where product_name ='"+p_name+"' and exists (select product_name from cart_table  where username ='"+user+"' and product_name='"+p_name+"')");
                                stat.executeUpdate("update cart_table set price = price + '"+p_price+"' * '"+quan+"' where product_name = '"+p_name+"' ");
                                JOptionPane.showMessageDialog(null,"Item added to cart");
                                con3.close();
                            }
                            con2.close();
                        }catch (ClassNotFoundException | SQLException ex) {                           
                                Connection con4=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95");
                                Statement stat2=con4.createStatement();
                                stat2.executeUpdate("insert into cart_table(username,product_name,quantity,price,pro_type) values ('"+user+"','"+p_name+"','"+quan+"','"+p_price+"','"+p_type+"')");
                                stat2.executeUpdate("update product_list set stock = stock - '"+quan+"' where product_name ='"+p_name+"' ");
                                stat2.executeUpdate("update cart_table set price =  ('"+p_price+"' * '"+quan+"') where product_name = '"+p_name+"' ");
                                JOptionPane.showMessageDialog(null,"Item added to cart");
                                con4.close();
                            Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
                        } 
                        
                    }
                    con.close();    
                }                
        }
        catch (SQLException ex) {
                Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_item1ActionPerformed

    private void cart_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cart_labelMouseClicked

        Cart r =new Cart(user);
        r.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cart_labelMouseClicked

    private void back_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_buttonActionPerformed
        MainPage r =new MainPage(user);
        r.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_back_buttonActionPerformed

    private void item3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item3ActionPerformed
        // TODO add your handling code here:
        
        int quan =1;       
        
        String p_name= "Plantation Pineapple";
        String p_price = "40";
        String p_type = "Rum";
        try {            
                Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95");               
                String query="select stock from product_list where product_name='"+p_name+"'";
                PreparedStatement pre=con.prepareStatement(query);
                ResultSet re=pre.executeQuery();
                if(re.next()){
                    int stockx =Integer.parseInt(re.getString("stock"));
                    
                    if(stockx == 0 || stockx < quan)
                        JOptionPane.showMessageDialog(null,"Item is out of stock");
                    else{
                        try {
                            Class.forName("oracle.jdbc.OracleDriver");
                            Connection con2=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95");               
                            String query2="update cart_table set quantity = quantity + '"+quan+"' where product_name='"+p_name+"'and  exists (select product_name from cart_table where username ='"+user+"' and product_name='"+p_name+"') ";
                            PreparedStatement pre2=con2.prepareStatement(query2);
                            ResultSet rs=pre2.executeQuery();
                            if(rs.next()){
                                Connection con3=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95"); 
                                Statement stat=con3.createStatement();
                                stat.executeUpdate("update product_list set stock = stock - '"+quan+"' where product_name ='"+p_name+"' and exists (select product_name from cart_table  where username ='"+user+"' and product_name='"+p_name+"')");
                                stat.executeUpdate("update cart_table set price = price + '"+p_price+"' * '"+quan+"' where product_name = '"+p_name+"' ");
                                JOptionPane.showMessageDialog(null,"Item added to cart");
                                con3.close();
                            }
                            con2.close();
                        }catch (ClassNotFoundException | SQLException ex) {                           
                                Connection con4=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95");
                                Statement stat2=con4.createStatement();
                                stat2.executeUpdate("insert into cart_table(username,product_name,quantity,price,pro_type) values ('"+user+"','"+p_name+"','"+quan+"','"+p_price+"','"+p_type+"')");
                                stat2.executeUpdate("update product_list set stock = stock - '"+quan+"' where product_name ='"+p_name+"' ");
                                stat2.executeUpdate("update cart_table set price =  ('"+p_price+"' * '"+quan+"') where product_name = '"+p_name+"' ");
                                JOptionPane.showMessageDialog(null,"Item added to cart");
                                con4.close();
                            Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
                        } 
                        
                    }
                    con.close();    
                }                
        }
        catch (SQLException ex) {
                Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_item3ActionPerformed

    private void item7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item7ActionPerformed
        // TODO add your handling code here:
        
        int quan =1;       
        
        String p_name= "Captain Morgan";
        String p_price = "25";
        String p_type = "Rum";
        try {            
                Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95");               
                String query="select stock from product_list where product_name='"+p_name+"'";
                PreparedStatement pre=con.prepareStatement(query);
                ResultSet re=pre.executeQuery();
                if(re.next()){
                    int stockx =Integer.parseInt(re.getString("stock"));
                    
                    if(stockx == 0 || stockx < quan)
                        JOptionPane.showMessageDialog(null,"Item is out of stock");
                    else{
                        try {
                            Class.forName("oracle.jdbc.OracleDriver");
                            Connection con2=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95");               
                            String query2="update cart_table set quantity = quantity + '"+quan+"' where product_name='"+p_name+"'and  exists (select product_name from cart_table where username ='"+user+"' and product_name='"+p_name+"') ";
                            PreparedStatement pre2=con2.prepareStatement(query2);
                            ResultSet rs=pre2.executeQuery();
                            if(rs.next()){
                                Connection con3=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95"); 
                                Statement stat=con3.createStatement();
                                stat.executeUpdate("update product_list set stock = stock - '"+quan+"' where product_name ='"+p_name+"' and exists (select product_name from cart_table  where username ='"+user+"' and product_name='"+p_name+"')");
                                stat.executeUpdate("update cart_table set price = price + '"+p_price+"' * '"+quan+"' where product_name = '"+p_name+"' ");
                                JOptionPane.showMessageDialog(null,"Item added to cart");
                                con3.close();
                            }
                            con2.close();
                        }catch (ClassNotFoundException | SQLException ex) {                           
                                Connection con4=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95");
                                Statement stat2=con4.createStatement();
                                stat2.executeUpdate("insert into cart_table(username,product_name,quantity,price,pro_type) values ('"+user+"','"+p_name+"','"+quan+"','"+p_price+"','"+p_type+"')");
                                stat2.executeUpdate("update product_list set stock = stock - '"+quan+"' where product_name ='"+p_name+"' ");
                                stat2.executeUpdate("update cart_table set price =  ('"+p_price+"' * '"+quan+"') where product_name = '"+p_name+"' ");
                                JOptionPane.showMessageDialog(null,"Item added to cart");
                                con4.close();
                            Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
                        } 
                        
                    }
                    con.close();    
                }                
        }
        catch (SQLException ex) {
                Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_item7ActionPerformed

    private void item5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item5ActionPerformed
        // TODO add your handling code here:
        
        int quan =1;       
        
        String p_name= "Goslings";
        String p_price = "30";
        String p_type = "Rum";
        try {            
                Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95");               
                String query="select stock from product_list where product_name='"+p_name+"'";
                PreparedStatement pre=con.prepareStatement(query);
                ResultSet re=pre.executeQuery();
                if(re.next()){
                    int stockx =Integer.parseInt(re.getString("stock"));
                    
                    if(stockx == 0 || stockx < quan)
                        JOptionPane.showMessageDialog(null,"Item is out of stock");
                    else{
                        try {
                            Class.forName("oracle.jdbc.OracleDriver");
                            Connection con2=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95");               
                            String query2="update cart_table set quantity = quantity + '"+quan+"' where product_name='"+p_name+"'and  exists (select product_name from cart_table where username ='"+user+"' and product_name='"+p_name+"') ";
                            PreparedStatement pre2=con2.prepareStatement(query2);
                            ResultSet rs=pre2.executeQuery();
                            if(rs.next()){
                                Connection con3=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95"); 
                                Statement stat=con3.createStatement();
                                stat.executeUpdate("update product_list set stock = stock - '"+quan+"' where product_name ='"+p_name+"' and exists (select product_name from cart_table  where username ='"+user+"' and product_name='"+p_name+"')");
                                stat.executeUpdate("update cart_table set price = price + '"+p_price+"' * '"+quan+"' where product_name = '"+p_name+"' ");
                                JOptionPane.showMessageDialog(null,"Item added to cart");
                                con3.close();
                            }
                            con2.close();
                        }catch (ClassNotFoundException | SQLException ex) {                           
                                Connection con4=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95");
                                Statement stat2=con4.createStatement();
                                stat2.executeUpdate("insert into cart_table(username,product_name,quantity,price,pro_type) values ('"+user+"','"+p_name+"','"+quan+"','"+p_price+"','"+p_type+"')");
                                stat2.executeUpdate("update product_list set stock = stock - '"+quan+"' where product_name ='"+p_name+"' ");
                                stat2.executeUpdate("update cart_table set price =  ('"+p_price+"' * '"+quan+"') where product_name = '"+p_name+"' ");
                                JOptionPane.showMessageDialog(null,"Item added to cart");
                                con4.close();
                            Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
                        } 
                        
                    }
                    con.close();    
                }                
        }
        catch (SQLException ex) {
                Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_item5ActionPerformed

    private void item2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item2ActionPerformed
        // TODO add your handling code here:
        
        int quan =1;       
        
        String p_name= "El Dorado";
        String p_price = "50";
        String p_type = "Rum";
        try {            
                Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95");               
                String query="select stock from product_list where product_name='"+p_name+"'";
                PreparedStatement pre=con.prepareStatement(query);
                ResultSet re=pre.executeQuery();
                if(re.next()){
                    int stockx =Integer.parseInt(re.getString("stock"));
                    
                    if(stockx == 0 || stockx < quan)
                        JOptionPane.showMessageDialog(null,"Item is out of stock");
                    else{
                        try {
                            Class.forName("oracle.jdbc.OracleDriver");
                            Connection con2=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95");               
                            String query2="update cart_table set quantity = quantity + '"+quan+"' where product_name='"+p_name+"'and  exists (select product_name from cart_table where username ='"+user+"' and product_name='"+p_name+"') ";
                            PreparedStatement pre2=con2.prepareStatement(query2);
                            ResultSet rs=pre2.executeQuery();
                            if(rs.next()){
                                Connection con3=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95"); 
                                Statement stat=con3.createStatement();
                                stat.executeUpdate("update product_list set stock = stock - '"+quan+"' where product_name ='"+p_name+"' and exists (select product_name from cart_table  where username ='"+user+"' and product_name='"+p_name+"')");
                                stat.executeUpdate("update cart_table set price = price + '"+p_price+"' * '"+quan+"' where product_name = '"+p_name+"' ");
                                JOptionPane.showMessageDialog(null,"Item added to cart");
                                con3.close();
                            }
                            con2.close();
                        }catch (ClassNotFoundException | SQLException ex) {                           
                                Connection con4=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95");
                                Statement stat2=con4.createStatement();
                                stat2.executeUpdate("insert into cart_table(username,product_name,quantity,price,pro_type) values ('"+user+"','"+p_name+"','"+quan+"','"+p_price+"','"+p_type+"')");
                                stat2.executeUpdate("update product_list set stock = stock - '"+quan+"' where product_name ='"+p_name+"' ");
                                stat2.executeUpdate("update cart_table set price =  ('"+p_price+"' * '"+quan+"') where product_name = '"+p_name+"' ");
                                JOptionPane.showMessageDialog(null,"Item added to cart");
                                con4.close();
                            Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
                        } 
                        
                    }
                    con.close();    
                }                
        }
        catch (SQLException ex) {
                Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_item2ActionPerformed

    private void item6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item6ActionPerformed
        // TODO add your handling code here:
        
        int quan =1;       
        
        String p_name= "Old Monk";
        String p_price = "15";
        String p_type = "Rum";
        try {            
                Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95");               
                String query="select stock from product_list where product_name='"+p_name+"'";
                PreparedStatement pre=con.prepareStatement(query);
                ResultSet re=pre.executeQuery();
                if(re.next()){
                    int stockx =Integer.parseInt(re.getString("stock"));
                    
                    if(stockx == 0 || stockx < quan)
                        JOptionPane.showMessageDialog(null,"Item is out of stock");
                    else{
                        try {
                            Class.forName("oracle.jdbc.OracleDriver");
                            Connection con2=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95");               
                            String query2="update cart_table set quantity = quantity + '"+quan+"' where product_name='"+p_name+"'and  exists (select product_name from cart_table where username ='"+user+"' and product_name='"+p_name+"') ";
                            PreparedStatement pre2=con2.prepareStatement(query2);
                            ResultSet rs=pre2.executeQuery();
                            if(rs.next()){
                                Connection con3=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95"); 
                                Statement stat=con3.createStatement();
                                stat.executeUpdate("update product_list set stock = stock - '"+quan+"' where product_name ='"+p_name+"' and exists (select product_name from cart_table  where username ='"+user+"' and product_name='"+p_name+"')");
                                stat.executeUpdate("update cart_table set price = price + '"+p_price+"' * '"+quan+"' where product_name = '"+p_name+"' ");
                                JOptionPane.showMessageDialog(null,"Item added to cart");
                                con3.close();
                            }
                            con2.close();
                        }catch (ClassNotFoundException | SQLException ex) {                           
                                Connection con4=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95");
                                Statement stat2=con4.createStatement();
                                stat2.executeUpdate("insert into cart_table(username,product_name,quantity,price,pro_type) values ('"+user+"','"+p_name+"','"+quan+"','"+p_price+"','"+p_type+"')");
                                stat2.executeUpdate("update product_list set stock = stock - '"+quan+"' where product_name ='"+p_name+"' ");
                                stat2.executeUpdate("update cart_table set price =  ('"+p_price+"' * '"+quan+"') where product_name = '"+p_name+"' ");
                                JOptionPane.showMessageDialog(null,"Item added to cart");
                                con4.close();
                            Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
                        } 
                        
                    }
                    con.close();    
                }                
        }
        catch (SQLException ex) {
                Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_item6ActionPerformed

    private void item8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item8ActionPerformed
        // TODO add your handling code here:
        
        int quan =1;       
        
        String p_name= "Bacardi";
        String p_price = "20";
        String p_type = "Rum";
        try {            
                Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95");               
                String query="select stock from product_list where product_name='"+p_name+"'";
                PreparedStatement pre=con.prepareStatement(query);
                ResultSet re=pre.executeQuery();
                if(re.next()){
                    int stockx =Integer.parseInt(re.getString("stock"));
                    
                    if(stockx == 0 || stockx < quan)
                        JOptionPane.showMessageDialog(null,"Item is out of stock");
                    else{
                        try {
                            Class.forName("oracle.jdbc.OracleDriver");
                            Connection con2=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95");               
                            String query2="update cart_table set quantity = quantity + '"+quan+"' where product_name='"+p_name+"'and  exists (select product_name from cart_table where username ='"+user+"' and product_name='"+p_name+"') ";
                            PreparedStatement pre2=con2.prepareStatement(query2);
                            ResultSet rs=pre2.executeQuery();
                            if(rs.next()){
                                Connection con3=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95"); 
                                Statement stat=con3.createStatement();
                                stat.executeUpdate("update product_list set stock = stock - '"+quan+"' where product_name ='"+p_name+"' and exists (select product_name from cart_table  where username ='"+user+"' and product_name='"+p_name+"')");
                                stat.executeUpdate("update cart_table set price = price + '"+p_price+"' * '"+quan+"' where product_name = '"+p_name+"' ");
                                JOptionPane.showMessageDialog(null,"Item added to cart");
                                con3.close();
                            }
                            con2.close();
                        }catch (ClassNotFoundException | SQLException ex) {                           
                                Connection con4=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95");
                                Statement stat2=con4.createStatement();
                                stat2.executeUpdate("insert into cart_table(username,product_name,quantity,price,pro_type) values ('"+user+"','"+p_name+"','"+quan+"','"+p_price+"','"+p_type+"')");
                                stat2.executeUpdate("update product_list set stock = stock - '"+quan+"' where product_name ='"+p_name+"' ");
                                stat2.executeUpdate("update cart_table set price =  ('"+p_price+"' * '"+quan+"') where product_name = '"+p_name+"' ");
                                JOptionPane.showMessageDialog(null,"Item added to cart");
                                con4.close();
                            Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
                        } 
                        
                    }
                    con.close();    
                }                
        }
        catch (SQLException ex) {
                Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_item8ActionPerformed

    private void item9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item9ActionPerformed
        // TODO add your handling code here:
        
        int quan =1;       
        
        String p_name= "Malibu Coconut";
        String p_price = "20";
        String p_type = "Rum";
        try {            
                Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95");               
                String query="select stock from product_list where product_name='"+p_name+"'";
                PreparedStatement pre=con.prepareStatement(query);
                ResultSet re=pre.executeQuery();
                if(re.next()){
                    int stockx =Integer.parseInt(re.getString("stock"));
                    
                    if(stockx == 0 || stockx < quan)
                        JOptionPane.showMessageDialog(null,"Item is out of stock");
                    else{
                        try {
                            Class.forName("oracle.jdbc.OracleDriver");
                            Connection con2=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95");               
                            String query2="update cart_table set quantity = quantity + '"+quan+"' where product_name='"+p_name+"'and  exists (select product_name from cart_table where username ='"+user+"' and product_name='"+p_name+"') ";
                            PreparedStatement pre2=con2.prepareStatement(query2);
                            ResultSet rs=pre2.executeQuery();
                            if(rs.next()){
                                Connection con3=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95"); 
                                Statement stat=con3.createStatement();
                                stat.executeUpdate("update product_list set stock = stock - '"+quan+"' where product_name ='"+p_name+"' and exists (select product_name from cart_table  where username ='"+user+"' and product_name='"+p_name+"')");
                                stat.executeUpdate("update cart_table set price = price + '"+p_price+"' * '"+quan+"' where product_name = '"+p_name+"' ");
                                JOptionPane.showMessageDialog(null,"Item added to cart");
                                con3.close();
                            }
                            con2.close();
                        }catch (ClassNotFoundException | SQLException ex) {                           
                                Connection con4=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95");
                                Statement stat2=con4.createStatement();
                                stat2.executeUpdate("insert into cart_table(username,product_name,quantity,price,pro_type) values ('"+user+"','"+p_name+"','"+quan+"','"+p_price+"','"+p_type+"')");
                                stat2.executeUpdate("update product_list set stock = stock - '"+quan+"' where product_name ='"+p_name+"' ");
                                stat2.executeUpdate("update cart_table set price =  ('"+p_price+"' * '"+quan+"') where product_name = '"+p_name+"' ");
                                JOptionPane.showMessageDialog(null,"Item added to cart");
                                con4.close();
                            Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
                        } 
                        
                    }
                    con.close();    
                }                
        }
        catch (SQLException ex) {
                Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_item9ActionPerformed

    private void item4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item4ActionPerformed
        // TODO add your handling code here:
        int quan =1;       
        
        String p_name= "Mount Gay";
        String p_price = "50";
        String p_type = "Rum";
        try {            
                Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95");               
                String query="select stock from product_list where product_name='"+p_name+"'";
                PreparedStatement pre=con.prepareStatement(query);
                ResultSet re=pre.executeQuery();
                if(re.next()){
                    int stockx =Integer.parseInt(re.getString("stock"));
                    
                    if(stockx == 0 || stockx < quan)
                        JOptionPane.showMessageDialog(null,"Item is out of stock");
                    else{
                        try {
                            Class.forName("oracle.jdbc.OracleDriver");
                            Connection con2=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95");               
                            String query2="update cart_table set quantity = quantity + '"+quan+"' where product_name='"+p_name+"'and  exists (select product_name from cart_table where username ='"+user+"' and product_name='"+p_name+"') ";
                            PreparedStatement pre2=con2.prepareStatement(query2);
                            ResultSet rs=pre2.executeQuery();
                            if(rs.next()){
                                Connection con3=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95"); 
                                Statement stat=con3.createStatement();
                                stat.executeUpdate("update product_list set stock = stock - '"+quan+"' where product_name ='"+p_name+"' and exists (select product_name from cart_table  where username ='"+user+"' and product_name='"+p_name+"')");
                                stat.executeUpdate("update cart_table set price = price + '"+p_price+"' * '"+quan+"' where product_name = '"+p_name+"' ");
                                JOptionPane.showMessageDialog(null,"Item added to cart");
                                con3.close();
                            }
                            con2.close();
                        }catch (ClassNotFoundException | SQLException ex) {                           
                                Connection con4=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Project", "shane95");
                                Statement stat2=con4.createStatement();
                                stat2.executeUpdate("insert into cart_table(username,product_name,quantity,price,pro_type) values ('"+user+"','"+p_name+"','"+quan+"','"+p_price+"','"+p_type+"')");
                                stat2.executeUpdate("update product_list set stock = stock - '"+quan+"' where product_name ='"+p_name+"' ");
                                stat2.executeUpdate("update cart_table set price =  ('"+p_price+"' * '"+quan+"') where product_name = '"+p_name+"' ");
                                JOptionPane.showMessageDialog(null,"Item added to cart");
                                con4.close();
                            Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
                        } 
                        
                    }
                    con.close();    
                }                
        }
        catch (SQLException ex) {
                Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_item4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RumPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RumPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RumPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RumPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RumPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_button;
    private javax.swing.JLabel cart_label;
    private javax.swing.JButton item1;
    private javax.swing.JButton item2;
    private javax.swing.JButton item3;
    private javax.swing.JButton item4;
    private javax.swing.JButton item5;
    private javax.swing.JButton item6;
    private javax.swing.JButton item7;
    private javax.swing.JButton item8;
    private javax.swing.JButton item9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
